### ISSUE TITLE
Cannot import name make_seq

### ISSUE THREAD

**Issue by changephilip** [mc-robinson/chain_joiner#1]
cannot import name make_seq
and please add the conda package to linux,
now it is in osx channel

**Comment by mc-robinson** [comment]
Linux conda packages are now available, thanks for reminding me!

As for the import problem, this will persist if you still want to download the code and run it locally. This was something annoying about relative imports that I had to do in order to get the conda packaging to work.

I believe if you go into chain_joiner.py and run_chain_joiner_online.py, you can fix the issue as follows. Wherever, it says
`` from chain_joiner import ``
just change it to:
``import``

For example, it should just say ``import make_seq``  in chain_joiner.py and not `` from chain_joiner import make_seq`` for a local package.

Hopefully, this works for you, but if not or if you know of a way to fix this annoying problem, please let me know.

Thanks and feel free to reach out with other issues.
